apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dockubernetes-k8s-dem
spec:
  selector:
    matchLabels:
      app: dockubernetes-k8s-dem
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dockubernetes-k8s-dem
    spec:
      containers:
      - name: dockubernetes-k8s-dem
        image: saurabhshcs/dockubernetes
        ports:
        - containerPort: 8080